In [1]:
# Libraries
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt

In [2]:
url = 'https://www.basketball-reference.com/leagues/NBA_2020_per_game.html'

In [3]:
response = requests.get(url).text

In [4]:
df = pd.read_html(url)[0]

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Steven Adams,C,26,OKC,63,63,26.7,4.5,7.6,...,.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,2,Bam Adebayo,PF,22,MIA,72,72,33.6,6.1,11.0,...,.691,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,3,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,...,.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,4,Kyle Alexander,C,23,MIA,2,0,6.5,0.5,1.0,...,NaN,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,5,Nickeil Alexander-Walker,SG,21,NOP,47,1,12.6,2.1,5.7,...,.676,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7

In [7]:
df.drop(columns='Rk', inplace=True)

In [8]:
df.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Steven Adams,C,26,OKC,63,63,26.7,4.5,7.6,.592,...,.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,Bam Adebayo,PF,22,MIA,72,72,33.6,6.1,11.0,.557,...,.691,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,.493,...,.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,Kyle Alexander,C,23,MIA,2,0,6.5,0.5,1.0,.500,...,NaN,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,Nickeil Alexander-Walker,SG,21,NOP,47,1,12.6,2.1,5.7,.368,...,.676,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7

In [9]:
df.isna().sum().sum()

78

In [10]:
df.isna().sum()

Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        2
3P         0
3PA        0
3P%       35
2P         0
2PA        0
2P%        6
eFG%       2
FT         0
FTA        0
FT%       33
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
dtype: int64

In [11]:
df.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Steven Adams,C,26,OKC,63,63,26.7,4.5,7.6,.592,...,.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,Bam Adebayo,PF,22,MIA,72,72,33.6,6.1,11.0,.557,...,.691,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,.493,...,.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,Kyle Alexander,C,23,MIA,2,0,6.5,0.5,1.0,.500,...,NaN,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,Nickeil Alexander-Walker,SG,21,NOP,47,1,12.6,2.1,5.7,.368,...,.676,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7

In [12]:
df.fillna(0, inplace=True)

In [13]:
df.isna().sum().sum()

0

In [14]:
len(df) - len(df[df.Player == 'Player'])

651

In [15]:
df.drop(df[df.Player == 'Player'].index, inplace=True)

In [16]:
len(df)

651

In [17]:
df.dtypes

Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

In [18]:
numeric_features = df.columns.drop(['Player', 'Pos', 'Tm'])

In [19]:
df[numeric_features]= df[numeric_features].applymap(lambda x: pd.to_numeric(x))

In [20]:
df.dtypes

Player     object
Pos        object
Age         int64
Tm         object
G           int64
GS          int64
MP        float64
FG        float64
FGA       float64
FG%       float64
3P        float64
3PA       float64
3P%       float64
2P        float64
2PA       float64
2P%       float64
eFG%      float64
FT        float64
FTA       float64
FT%       float64
ORB       float64
DRB       float64
TRB       float64
AST       float64
STL       float64
BLK       float64
TOV       float64
PF        float64
PTS       float64
dtype: object

In [21]:
df.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Steven Adams,C,26,OKC,63,63,26.7,4.5,7.6,0.592,...,0.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,Bam Adebayo,PF,22,MIA,72,72,33.6,6.1,11.0,0.557,...,0.691,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,0.493,...,0.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,Kyle Alexander,C,23,MIA,2,0,6.5,0.5,1.0,0.500,...,0.000,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,Nickeil Alexander-Walker,SG,21,NOP,47,1,12.6,2.1,5.7,0.368,...,0.676,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7

In [22]:
df.G.describe()

count    651.00000
mean      38.21659
std       22.94443
min        1.00000
25%       15.50000
50%       41.00000
75%       59.00000
max       74.00000
Name: G, dtype: float64

In [23]:
# Minimum games played to be considered is 70% of Team's games
min_games = 0.7 * df.G.max()

df_min_games = df[df.G > min_games]

In [24]:
df.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [27]:
df.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [30]:
df.Pos.unique()

array(['C', 'PF', 'SG', 'PG', 'SF', 'PF-SF', 'PF-C', 'SF-SG', 'SF-C',
       'SF-PF', 'SG-SF', 'C-PF', 'SG-PG', 'PG-SG'], dtype=object)

In [31]:
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')

In [32]:
mvp_link = soup.find(id='info').find_all('p')[3].find('a').attrs['href']

In [33]:
mvp_page = requests.get('https://www.basketball-reference.com' + mvp_link)
mvp_page

In [34]:
mvp_data = BeautifulSoup(mvp_page.content, 'html.parser')

In [35]:
mvp_data.find(class_='players').find('img')['src']

'https://www.basketball-reference.com/req/202104203/images/players/antetgi01.jpg'

In [36]:
mvp_name = mvp_data.find(class_='players').find('span').text

In [37]:
df[df.Player.str.contains(mvp_name)]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
12,Giannis Antetokounmpo,PF,25,MIL,63,63,30.4,10.9,19.7,0.553,...,0.633,2.2,11.4,13.6,5.6,1.0,1.0,3.7,3.1,29.5

In [38]:
df.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [67]:
percentage_features = ['FG%', 'FT%', '3P%', '2P%', 'eFG%', 'FT%' ]

b

       FG%    FT%    3P%    2P%   eFG%    FT%
0    0.592  0.582  0.333  0.594  0.593  0.582
1    0.557  0.691  0.143  0.564  0.558  0.691
2    0.493  0.827  0.389  0.519  0.532  0.827
3    0.500  0.000  0.000  0.500  0.500  0.000
4    0.368  0.676  0.346  0.391  0.455  0.676
..     ...    ...    ...    ...    ...    ...
672  0.437  0.860  0.361  0.501  0.519  0.860
673  0.524  0.682  0.240  0.577  0.543  0.682
674  0.250  0.000  0.000  0.250  0.250  0.000
675  0.569  0.737  0.000  0.569  0.569  0.737
676  0.613  0.747  0.000  0.616  0.613  0.747

[651 rows x 6 columns]

In [61]:
float_features = df.select_dtypes(include='float')
float_features

,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,26.7,4.5,7.6,0.592,0.0,0.0,0.333,4.5,7.5,0.594,...,0.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,33.6,6.1,11.0,0.557,0.0,0.2,0.143,6.1,10.8,0.564,...,0.691,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,33.1,7.4,15.0,0.493,1.2,3.0,0.389,6.2,12.0,0.519,...,0.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,6.5,0.5,1.0,0.500,0.0,0.0,0.000,0.5,1.0,0.500,...,0.000,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,12.6,2.1,5.7,0.368,1.0,2.8,0.346,1.1,2.8,0.391,...,0.676,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,35.3,9.1,20.8,0.437,3.4,9.5,0.361,5.7,11.4,0.501,...,0.860,0.5,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6
673,23.1,4.3,8.3,0.524,0.3,1.3,0.240,4.0,7.0,0.577,...,0.682,2.8,4.3,7.1,1.5,0.7,0.4,1.3,2.4,11.1
674,2.0,0.5,2.0,0.250,0.0,0.0,0.000,0.5,2.0,0.250,...,0.000,1.5,0.5,2.0,0.0,0.0,0.0,0.0,0.0,1.0
675,10.0,1.9,3.3,0.569,0.0,0.0,0.000,1.9,3.3,0.569,...,0.737,0.8,2.2,3.0,0.3,0.3,0.2,0.5,1.2,4.4
676,18.4,3.3,5.3,0.613,0.0,0.0,0.000,3.3,5.3,0.616,...,0.747,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3

In [84]:
df_min_games[(df_min_games['FT%'] == 1 )| (df_min_games['3P%'] == 1) | (df_min_games['FG%'] == 1) |
            (df_min_games['FT%'] == 0 )| (df_min_games['3P%'] == 0) | (df_min_games['FG%'] == 0)]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
6,Jarrett Allen,C,21,BRK,70,64,26.5,4.3,6.6,0.649,...,0.633,3.1,6.5,9.6,1.6,0.6,1.3,1.1,2.3,11.1
58,Bismack Biyombo,C,27,CHO,53,29,19.4,2.8,5.2,0.543,...,0.603,2.3,3.5,5.8,0.9,0.2,0.9,0.9,2.2,7.4
75,Tony Bradley,C,22,UTA,58,3,11.4,2.2,3.3,0.667,...,0.652,1.9,2.7,4.6,0.4,0.2,0.6,0.5,2.0,4.9
119,Willie Cauley-Stein,C,26,TOT,54,39,20.3,3.2,5.6,0.579,...,0.606,1.6,4.3,5.8,1.3,0.9,1.1,0.7,2.2,7.2
237,Rudy Gobert,C,27,UTA,68,68,34.3,5.7,8.2,0.693,...,0.630,3.4,10.1,13.5,1.5,0.8,2.0,1.9,3.2,15.1
272,Montrezl Harrell,C,26,LAC,63,2,27.8,7.5,12.9,0.580,...,0.658,2.6,4.5,7.1,1.7,0.6,1.1,1.7,2.3,18.6
351,DeAndre Jordan,C,31,BRK,56,6,22.0,3.4,5.1,0.666,...,0.680,2.5,7.5,10.0,1.9,0.3,0.9,1.3,2.0,8.3
514,Mason Plumlee,C,29,DEN,61,1,17.3,2.9,4.7,0.615,...,0.535,1.6,3.6,5.2,2.5,0.5,0.6,1.3,2.3,7.2
515,Jakob Poeltl,C,24,SAS,66,18,17.7,2.5,4.0,0.624,...,0.465,2.0,3.7,5.7,1.8,0.6,1.4,0.8,1.9,5.6
545,Mitchell Robinson,C,21,NYK,61,7,23.1,4.1,5.6,0.742,...,0.568,3.0,4.0,7.0,0.6,0.9,2.0,0.6,3.2,9.7
579,Tony Snell,SF,28,DET,59,57,27.8,2.9,6.5,0.445,...,1.000,0.2,1.7,1.9,2.2,0.5,0.3,0.5,1.7,8.0
676,Ivica Zubac,C,22,LAC,72,70,18.4,3.3,5.3,0.613,...,0.747,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3

In [85]:
len(df_min_games)

248

In [87]:
df_min_games.drop(df_min_games[(df_min_games['FT%'] == 1 )| (df_min_games['3P%'] == 1) | (df_min_games['FG%'] == 1) |
            (df_min_games['FT%'] == 0 )| (df_min_games['3P%'] == 0) | (df_min_games['FG%'] == 0)].index, inplace=True)

/home/tomas/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pandas/core/frame.py:4305: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [88]:
len(df_min_games)

236